# fly.toml app configuration file generated for netify-api-lingering-leaf-3047 on 2025-05-16T19:22:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'netify-api-lingering-leaf-3047'
primary_region = 'sea'

[build]
  dockerfile = 'api/backend/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
