app = "netify-api"
primary_region = "sjc" # Silicon Valley region, change as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 